description: Convert specified assets into Cloud Optimized GeoTIFFs
environment:
  GDAL_DATA: /opt/share/gdal
  PROJ_LIB: /opt/share/proj
lambda:
  memorySize: 1024
  timeout: 900
  layers:
    - arn:aws:lambda:${self:provider.region}:552188055668:layer:geolambda:2
    - arn:aws:lambda:${self:provider.region}:552188055668:layer:geolambda-python:1
python_requirements:
  - rasterio==1.2.8
  - rio-cogeo~=1.1.10
