Resources:
  # Main data bucket
  Data:
    Type: AWS::S3::Bucket
  # Bucket for storing input catalogs
  Catalogs:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 10
            Prefix: batch/
            Status: Enabled
          - ExpirationInDays: 10
            Prefix: payloads/
            Status: Enabled
  # SNS Topic for adding input data to Cirrus
  QueueTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: ${self:service}-${self:provider.stage}-queue
  # SNS Topic for adding input data to Cirrus
  PublishTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: ${self:service}-${self:provider.stage}-publish
  # Allow anyone to subscribe to publish topic
  #PublishTopicPolicy:
  #  Type: 'AWS::SNS::TopicPolicy'
  #  Properties:
  #    Topics:
  #      - !Ref PublishTopic
  #    PolicyDocument:
  #      Statement:
  #        - Sid: public-sns-subscriptions
  #          Effect: Allow
  #          Principal: "*"
  #          Action:
  #            - sns:Subscribe
  #          Resource:
  #            - arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:service}-${self:provider.stage}-publish
  # Process Queue
  ProcessQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-process
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ProcessDeadLetterQueue.Arn
        maxReceiveCount: 2
  ProcessDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-process-dead-letter
  ProcessQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref ProcessQueue
      PolicyDocument:
        Statement:
          - Sid: allow-sqs-sendmessage
            Effect: Allow
            Principal:
              AWS: "*"
            Action: SQS:SendMessage
            Resource: !GetAtt ProcessQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn:
                  - !Ref QueueTopic
                  - !Ref PublishTopic
  ProcessQueueSubsciption:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt ProcessQueue.Arn
      Protocol: sqs
      Region: "#{AWS::Region}"
      TopicArn: !Ref QueueTopic
  StateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: input_collections
          AttributeType: S
        - AttributeName: id
          AttributeType: S
        - AttributeName: output_collections
          AttributeType: S
        - AttributeName: current_state
          AttributeType: S
      KeySchema:
        - AttributeName: input_collections
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: "input_state"
          KeySchema:
            - AttributeName: input_collections
              KeyType: HASH
            - AttributeName: current_state
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      GlobalSecondaryIndexes:
        - IndexName: "output_state"
          KeySchema:
            - AttributeName: output_collections
              KeyType: HASH
            - AttributeName: current_state
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:service}-${self:provider.stage}-state