Resources:
  GeoLambdaAsBatchJob:
    Type: "AWS::Batch::JobDefinition"
    Properties:
      JobDefinitionName: "#{AWS::StackName}-geolambda-as-batch"
      Type: Container
      Parameters:
        lambda_function: ""
        url: ""
      ContainerProperties:
        Command:
          - run
          - Ref::lambda_function
          - Ref::url
        Environment:
          - Name: GDAL_DATA
            Value: /usr/local/share/gdal
          - Name: PROJ_LIB
            Value: /usr/local/share/proj
        Memory: ${self:custom.batch.GeoLambdaAsBatchJob.Memory}
        Vcpus: ${self:custom.batch.GeoLambdaAsBatchJob.Vcpus}
        Image: "cirrusgeo/run-geolambda:0.2.1"
      RetryStrategy:
        Attempts: 1
  LambdaAsBatchJob:
    Type: "AWS::Batch::JobDefinition"
    Properties:
      JobDefinitionName: "#{AWS::StackName}-lambda-as-batch"
      Type: Container
      Parameters:
        lambda_function: ""
        url: ""
      ContainerProperties:
        Command:
          - run
          - Ref::lambda_function
          - Ref::url
        Environment:
        Memory: ${self:custom.batch.LambdaAsBatchJob.Memory}
        Vcpus: ${self:custom.batch.LambdaAsBatchJob.Vcpus}
        Image: "cirrusgeo/run-lambda:0.2.1"
      RetryStrategy:
        Attempts: 1
