description: Copy specified assets from Item(s) to an S3 bucket
lambda:
  memorySize: 768
  timeout: 60
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - !Join
          - ''
          - - 'arn:aws:s3:::'
            - ${self:provider.environment.CIRRUS_DATA_BUCKET}
            - '*'
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:GetBucketLocation"
      Resource: "*"
    - Effect: "Allow"
      Action: secretsmanager:GetSecretValue
      Resource:
        - arn:aws:secretsmanager:#{AWS::Region}:#{AWS::AccountId}:secret:cirrus-creds-*
batch:
  resources:
    Resources:
      CopyAssetsAsBatchJob:
        Type: "AWS::Batch::JobDefinition"
        Properties:
          JobDefinitionName: '#{AWS::StackName}-copy-assets-as-batch'
          Type: Container
          Parameters:
            url: ""
          ContainerProperties:
            Command:
              - run
              - ${self:service}-${self:provider.stage}-copy-assets
              - Ref::url
            Memory: 12000
            Vcpus: 1
            Image: 'cirrusgeo/run-geolambda:0.2.1'
          RetryStrategy:
            Attempts: 1
      CopyAssetsComputeEnvironment:
        Type: AWS::Batch::ComputeEnvironment
        Properties:
          Type: MANAGED
          ServiceRole:
            Fn::GetAtt: [ BatchServiceRole, Arn ]
          ComputeResources:
            MaxvCpus: 1000
            SecurityGroupIds: ${self:custom.batch.SecurityGroupIds}
            Subnets: ${self:custom.batch.Subnets}
            InstanceTypes:
              - optimal
            Type: SPOT
            AllocationStrategy: BEST_FIT_PROGRESSIVE
            SpotIamFleetRole:
              Fn::GetAtt: [ EC2SpotRole, Arn ]
            MinvCpus: 0
            InstanceRole:
              Fn::GetAtt: [ BatchInstanceProfile, Arn ]
            Tags: {"Name": "Batch Instance - #{AWS::StackName}"}
            DesiredvCpus: 0
          State: ENABLED
      CopyAssetsJobQueue:
        Type: AWS::Batch::JobQueue
        Properties:
          ComputeEnvironmentOrder:
            - Order: 1
              ComputeEnvironment: !Ref CopyAssetsComputeEnvironment
          State: ENABLED
          Priority: 1
          JobQueueName: '#{AWS::StackName}-copy-assets-jq'
