description: Create a preview and/or thumbnail from one or more assets
environment:
  GDAL_DATA: /opt/share/gdal
  PROJ_LIB: /opt/share/proj
lambda:
  memorySize: 1024
  timeout: 900
  layers:
    - arn:aws:lambda:${self:provider.region}:552188055668:layer:geolambda:2
    - arn:aws:lambda:${self:provider.region}:552188055668:layer:geolambda-python:1
  pythonRequirements:
    include:
      - rasterio==1.2.8
      - rio-cogeo~=1.1.10
