description: Publish resulting STAC Collections and Items to catalog, and optionally SNS
lambda:
  memorySize: 128
  timeout: 30
  handler: lambda_function.lambda_handler
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - SNS:Publish
      Resource: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:*
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - !GetAtt StateTable.Arn
        - !Join ["", [!GetAtt StateTable.Arn, "/index/*"]]
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:GetBucketLocation"
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource: "*"
    - Effect: "Allow"
      Action: secretsmanager:GetSecretValue
      Resource:
        - arn:aws:secretsmanager:#{AWS::Region}:#{AWS::AccountId}:secret:cirrus-creds-*
