name: Build lambda dist zip

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build-lambda-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install '.'
      - name: Build lambda zip
        run: ./bin/build-lambda-dist.bash
      - name: Add to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cirrus-lambda-dist.zip
