name: Build and release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - name: Build package
        run: uv build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags')
        with:
          name: dist-{github.ref}
          path: dist/
          overwrite: true
          if-no-files-found: error

  release-package:
    if: startsWith(github.ref, 'refs/tags')
    needs: build-package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/cirrus-geo
    permissions:
      id-token: write
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v5
        with:
          name: dist-{github.ref}
          path: dist/
      - name: Upload release
        uses: pypa/gh-action-pypi-publish@release/v1
