name: Build Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build-package:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/cirrus-geo
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
      - name: Build package
        run: uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.ref, 'refs/tags')
